# Generated by Django 4.1.2 on 2023-01-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subject_teacher_bio_teacher_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.CharField(default='https://acadtutor.blob.core.windows.net/acadtutor/6769264_60111.jpg', max_length=100),
        ),
    ]
