# Generated by Django 4.1.2 on 2023-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
