# Generated by Django 4.1.2 on 2023-05-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_teacher_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering'), ('ET', 'Electronics and Communication Engineering'), ('EE', 'Electrical and Electronics Engineering')], max_length=10, null=True),
        ),
    ]
