# Generated by Django 4.1.2 on 2023-05-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_teacher_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='bio',
            new_name='about',
        ),
    ]
