name : Push backend to frontend prod
on:
  push:
    branches:
      - main
    paths:
      - 'backend'
  pull_request:
    branches:
      - main
    paths:
      - 'backend'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: pushing front end to production-frontend
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./backend
        publish_branch: production_backend
