# Generated by Django 4.1.2 on 2023-04-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_ans_id_alter_exam_id_alter_options_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='negative_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='postive_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='responses',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
