name: Push to backend_prod
on:
  push:	
    branches:	
      - main
    paths:
      - backend/**

jobs:
  deploy:
    name: Push to backend_prod
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: push to branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: backend_prod
        FOLDER: backend
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAR_GLOBS_FILE: ".clear-target-files"
