name: Push to frontend_prod
on:
  push:	
    branches:	
      - main
    paths:
      - frontend/**

jobs:
  deploy:
    name: Push to frontend_prod
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: push to branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: frontend_prod
        FOLDER: frontend
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
